version: 0.0
os: linux
files:
  - source: /
    destination: /code
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      runas: root
  AfterInstall:
    - location: scripts/afterInstall.sh
      runas: root
  ApplicationStart:
    - location: scripts/applicationStart.sh
      runas: root
  # ApplicationStop:
    # - location: scripts/applicationStop.sh
      # runas: root
permissions:
  - object: /code/scripts
    owner: root
    mode: 777
    type:
      - directory