version: 0.0
os: linux
files:
  - source: /
    destination: /code
hooks:
  ApplicationStop:
    - location:scripts/applicationStop.sh
      runas: ec2-user
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      runas: root
  AfterInstall:
    - location: scripts/afterInstall.sh
      runas: root
  ApplicationStart:
    - location: scripts/applicationStart.sh
      runas: ec2-user
permissions:
  - object: /code/scripts
    owner: root
    mode: 777
    type:
      - directory
